on:
  push:
    branches:
      - main
name: Deploy Main on Push
jobs:
  web-deploy:
    name: Deploy to the Staging
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use production env
      run: cp .env.example .env

    - name: Update .env
      run: |
        sed -i 's/ACTIONS_URL/https://carrental.infinitycode.com.au/g' .env
        sed -i 's/ACTIONS_DB_NAME/Car_rental/g' .env
        sed -i 's/ACTIONS_DB_USER/${{ secrets.db_user }}/g' .env
        sed -i 's/ACTIONS_DB_PASSWORD/${{ secrets.db_password }}/g' .env
    
    - name: Install vendors
      run: composer install --no-dev --optimize-autoloader

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: 92.204.221.10
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}