name: Deploy Main on Push
on:
  push:
    branches:
      - main

env:
  PRODUCTION_URL: ${{ secrets.url }}
  PRODUCTION_APP_KEY: ${{ secrets.app_key }}
  PRODUCTION_DB_NAME: "Car_rental"
  PRODUCTION_DB_USER: ${{ secrets.db_user }}
  PRODUCTION_DB_PASSWORD: ${{ secrets.db_password }}
  STRIPE_KEY: ${{ secrets.stripe_key }}
  STRIPE_SECRET: ${{ secrets.stripe_secret }}
  FTP_SERVER: "92.204.221.10"
  FTP_USERNAME: ${{ secrets.ftp_username }}
  FTP_PASSWORD: ${{ secrets.ftp_password }}

jobs:
  web-deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Use production env
        run: cp .env.production .env

      - name: Update .env
        run: |
          sed -i "s/ACTIONS_URL/${{ env.PRODUCTION_URL }}/g" .env
          sed -i "s/ACTIONS_APP_KEY/${{ env.PRODUCTION_APP_KEY }}/g" .env
          sed -i "s/ACTIONS_DB_NAME/${{ env.PRODUCTION_DB_NAME }}/g" .env
          sed -i "s/ACTIONS_DB_USER/${{ env.PRODUCTION_DB_USER }}/g" .env
          sed -i "s/ACTIONS_DB_PASSWORD/${{ env.PRODUCTION_DB_PASSWORD }}/g" .env
          sed -i 's|'ACTIONS_DB_PASSWORD'|'${{ env.PRODUCTION_DB_PASSWORD }}'|g'
          sed -i "s/ACTIONS_STRIPE_KEY/${{ env.STRIPE_KEY }}/g" .env
          sed -i "s/ACTIONS_STRIPE_SECRET/${{ env.STRIPE_SECRET }}/g" .env

      - name: Install dependencies
        run: |
          composer install --no-dev --optimize-autoloader
          npm ci --no-optional

      - name: Build assets
        run: npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ env.FTP_SERVER }}
          username: ${{ env.FTP_USERNAME }}
          password: ${{ env.FTP_PASSWORD }}

      - name: Clean up
        run: |
          composer install --no-dev --optimize-autoloader --no-interaction --no-progress --no-suggest
          npm ci --production
          php artisan clear-compiled
          php artisan optimize